# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
      exclude: ^tests/fixtures/.*
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

  - repo: local
    hooks:
    - id: cargo-fmt
      name: cargo-fmt
      description: Format files with cargo fmt.
      entry: cargo fmt
      language: rust
      types: [rust]
      args: ["--"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
    - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
    - id: mypy
      files: >
        (?x)^(
          .*\.pyi|
          tests/test_api\.py
        )$
